export const images = {
  logo:              '/assets/images/logo.png',
  // Semantic keys
  operativePortrait: '/assets/images/guard-premium.jpg',
  operationalAssets: '/assets/images/elite-assets.jpg',
  stadiumOperations: '/assets/images/operations-collage.jpg',
  vipDetail:         '/assets/images/vip-protection.jpg',
  patrolVehicle:     '/assets/images/patrol-vehicle.jpg',
  clientLogoGrid:    '/assets/images/deployments.jpg',
  eventVenue:        '/assets/images/event-solutions.jpg',
  // Legacy keys
  guardPremium:      '/assets/images/guard-premium.jpg',
  eliteAssets:       '/assets/images/elite-assets.jpg',
  operationsCollage: '/assets/images/operations-collage.jpg',
  vipProtection:     '/assets/images/vip-protection.jpg',
  patrolVehicleImg:  '/assets/images/patrol-vehicle.jpg',
  deployments:       '/assets/images/deployments.jpg',
  eventSolutions:    '/assets/images/event-solutions.jpg',
  // Site_Images — real operational photos
  eventGallery:      '/assets/images/event_gallery.jpg',
  eventPix1:         '/assets/images/event_pix_gallery.jpg',
  eventPix2:         '/assets/images/event_pix_gallery_02.jpg',
  fullSquad:         '/assets/images/full squad.jpg',
  gallery:           '/assets/images/gallery.jpg',
  hilux:             '/assets/images/hilux.jpg',
  lexusSuv:          '/assets/images/lexus_suv.jpg',
  prado:             '/assets/images/prado2.jpg',
  squad:             '/assets/images/squad.jpg',
  squad2:            '/assets/images/squad2.jpg',
  squad3:            '/assets/images/squad3.jpg',
  timeless01:        '/assets/images/timeless_01.jpg',
} as const
